export const audioMap = {
  "Class 3A asked their friends: what is your favourite fruit? They wrote tally marks on a page, but nobody could tell which fruit won at a glance. How can we turn these tally marks into a picture that tells the story instantly?": "/assets/audio/class_3a_asked_their_friends_what_is_your_favourite_fruit_they_wrote_tally_marks_on_a_page_but_nobody_could_tell_which_fruit_won_at_a_glance_how_can_we_turn_these_tally_marks_into_a_picture_that_tells_the_story_instantly_0.mp3",
  "A Bar Graph! Tall bars for popular fruits, short bars for less popular ones. Let's explore how to build one in the story.": "/assets/audio/a_bar_graph_tall_bars_for_popular_fruits_short_bars_for_less_popular_ones_lets_explore_how_to_build_one_in_the_story_1.mp3",
  "Class 3A asked their friends about their favourite fruit and made tally marks. Robo says every survey needs to be collected fairly and counted carefully before it becomes a graph!": "/assets/audio/class_3a_asked_their_friends_about_their_favourite_fruit_and_made_tally_marks_robo_says_every_survey_needs_to_be_collected_fairly_and_counted_carefully_before_it_becomes_a_graph_2.mp3",
  "Every bar graph needs a Title, a horizontal x-axis for categories, and a vertical y-axis for the scale. Robo always draws these first, like building the frame of a house before decorating it.": "/assets/audio/every_bar_graph_needs_a_title_a_horizontal_xaxis_for_categories_and_a_vertical_yaxis_for_the_scale_robo_always_draws_these_first_like_building_the_frame_of_a_house_before_decorating_it_3.mp3",
  "Robo picks a scale that goes up in equal jumps — 0, 2, 4, 6, 8, 10 — then draws each bar to match its data value. Every bar is the same width, with the same gap in between, only the height changes!": "/assets/audio/robo_picks_a_scale_that_goes_up_in_equal_jumps_0_2_4_6_8_10_then_draws_each_bar_to_match_its_data_value_every_bar_is_the_same_width_with_the_same_gap_in_between_only_the_height_changes_4.mp3",
  "Once every bar is labelled, the graph tells its own story! Banana got the tallest bar with 10 votes, and Papaya the shortest with just 2. Now anyone can read the results in seconds — no counting tallies needed!": "/assets/audio/once_every_bar_is_labelled_the_graph_tells_its_own_story_banana_got_the_tallest_bar_with_10_votes_and_papaya_the_shortest_with_just_2_now_anyone_can_read_the_results_in_seconds_no_counting_tallies_needed_5.mp3",
  "Welcome to the Graph Anatomy Spinner! Drag the graph to spin it, and toggle highlights to explore the title, axes, scale, bars and labels.": "/assets/audio/welcome_to_the_graph_anatomy_spinner_drag_the_graph_to_spin_it_and_toggle_highlights_to_explore_the_title_axes_scale_bars_and_labels_6.mp3",
  "In the Bar Value Reader, let's read the data. Tap on a bar or use the number pad to fill in its value.": "/assets/audio/in_the_bar_value_reader_lets_read_the_data_tap_on_a_bar_or_use_the_number_pad_to_fill_in_its_value_7.mp3",
  "Let's match the graph parts. Match each description on the left with its correct part name on the right.": "/assets/audio/lets_match_the_graph_parts_match_each_description_on_the_left_with_its_correct_part_name_on_the_right_8.mp3",
  "Welcome to the Construction Sandbox! Tell me which bars are tallest, even, or above average, then click watch it to see them grow!": "/assets/audio/welcome_to_the_construction_sandbox_tell_me_which_bars_are_tallest_even_or_above_average_then_click_watch_it_to_see_them_grow_9.mp3",
  "Excellent!": "/assets/audio/excellent_10.mp3",
  "Well done!": "/assets/audio/well_done_11.mp3",
  "Brilliant!": "/assets/audio/brilliant_12.mp3",
  "You got it!": "/assets/audio/you_got_it_13.mp3",
  "Super smart!": "/assets/audio/super_smart_14.mp3",
  "Great reading!": "/assets/audio/great_reading_15.mp3",
  "Oh no! You have run out of hearts. Let's retry this world.": "/assets/audio/oh_no_you_have_run_out_of_hearts_lets_retry_this_world_16.mp3",
  "Amazing work! Let's reflect on everything you've learned about bar graphs.": "/assets/audio/amazing_work_lets_reflect_on_everything_youve_learned_about_bar_graphs_17.mp3",
  "Favourite Fruits in Class 3A": "/assets/audio/favourite_fruits_in_class_3a_18.mp3",
  "Pets Owned by Class 3A": "/assets/audio/pets_owned_by_class_3a_19.mp3",
  "Weather in April (Days)": "/assets/audio/weather_in_april_days_20.mp3",
  "Sports Day Medals Won": "/assets/audio/sports_day_medals_won_21.mp3",
  "Look at the graph. How many students chose Mango as their favourite fruit?": "/assets/audio/look_at_the_graph_how_many_students_chose_mango_as_their_favourite_fruit_22.mp3",
  "Find the bar labelled Mango, then look at how tall it is.": "/assets/audio/find_the_bar_labelled_mango_then_look_at_how_tall_it_is_23.mp3",
  "Trace from the top of the Mango bar across to the scale on the left.": "/assets/audio/trace_from_the_top_of_the_mango_bar_across_to_the_scale_on_the_left_24.mp3",
  "How many students chose Papaya as their favourite fruit?": "/assets/audio/how_many_students_chose_papaya_as_their_favourite_fruit_25.mp3",
  "Papaya has the shortest bar in this graph.": "/assets/audio/papaya_has_the_shortest_bar_in_this_graph_26.mp3",
  "The Papaya bar only reaches up to 2 on the scale.": "/assets/audio/the_papaya_bar_only_reaches_up_to_2_on_the_scale_27.mp3",
  "Which fruit got the MOST votes in the graph?": "/assets/audio/which_fruit_got_the_most_votes_in_the_graph_28.mp3",
  "Look for the TALLEST bar in the whole graph.": "/assets/audio/look_for_the_tallest_bar_in_the_whole_graph_29.mp3",
  "The tallest bar reaches all the way up to 10.": "/assets/audio/the_tallest_bar_reaches_all_the_way_up_to_10_30.mp3",
  "Which fruit got the FEWEST votes?": "/assets/audio/which_fruit_got_the_fewest_votes_31.mp3",
  "Look for the SHORTEST bar in the graph.": "/assets/audio/look_for_the_shortest_bar_in_the_graph_32.mp3",
  "The shortest bar only reaches 2 on the scale.": "/assets/audio/the_shortest_bar_only_reaches_2_on_the_scale_33.mp3",
  "What does the scale on the left side of this graph count in steps of?": "/assets/audio/what_does_the_scale_on_the_left_side_of_this_graph_count_in_steps_of_34.mp3",
  "Look at the numbers going up the y-axis: 0, 2, 4, 6...": "/assets/audio/look_at_the_numbers_going_up_the_yaxis_0_2_4_6_35.mp3",
  "Each gridline jumps up by 2 from the one below it.": "/assets/audio/each_gridline_jumps_up_by_2_from_the_one_below_it_36.mp3",
  "True or False: In a bar graph, a taller bar always means a bigger number.": "/assets/audio/true_or_false_in_a_bar_graph_a_taller_bar_always_means_a_bigger_number_37.mp3",
  "Think about what the height of each bar represents.": "/assets/audio/think_about_what_the_height_of_each_bar_represents_38.mp3",
  "The height of a bar always matches its value on the scale.": "/assets/audio/the_height_of_a_bar_always_matches_its_value_on_the_scale_39.mp3",
  "How many Dogs are shown in the graph?": "/assets/audio/how_many_dogs_are_shown_in_the_graph_40.mp3",
  "Find the Dog bar and trace it up to the scale.": "/assets/audio/find_the_dog_bar_and_trace_it_up_to_the_scale_41.mp3",
  "The Dog bar reaches 8 on the y-axis.": "/assets/audio/the_dog_bar_reaches_8_on_the_yaxis_42.mp3",
  "Are there MORE Cats or MORE Dogs?": "/assets/audio/are_there_more_cats_or_more_dogs_43.mp3",
  "Compare the height of the Cat bar and the Dog bar.": "/assets/audio/compare_the_height_of_the_cat_bar_and_the_dog_bar_44.mp3",
  "Cat = 6, Dog = 8. Which number is bigger?": "/assets/audio/cat_6_dog_8_which_number_is_bigger_45.mp3",
  "How many MORE Fish are there than Hamsters?": "/assets/audio/how_many_more_fish_are_there_than_hamsters_46.mp3",
  "Fish = 12, Hamster = 4. Subtract to find the difference.": "/assets/audio/fish_12_hamster_4_subtract_to_find_the_difference_47.mp3",
  "12 minus 4 equals...": "/assets/audio/12_minus_4_equals_48.mp3",
  "How many pets are there altogether in this graph?": "/assets/audio/how_many_pets_are_there_altogether_in_this_graph_49.mp3",
  "Add up the values of ALL the bars: Fish + Cat + Dog + Hamster.": "/assets/audio/add_up_the_values_of_all_the_bars_fish_cat_dog_hamster_50.mp3",
  "12 + 6 + 8 + 4 = ?": "/assets/audio/12_6_8_4_51.mp3",
  "In this graph, what is shown on the x-axis (the bottom line)?": "/assets/audio/in_this_graph_what_is_shown_on_the_xaxis_the_bottom_line_52.mp3",
  "The x-axis is the horizontal line at the bottom.": "/assets/audio/the_xaxis_is_the_horizontal_line_at_the_bottom_53.mp3",
  "It lists the categories: Fish, Cat, Dog, Hamster.": "/assets/audio/it_lists_the_categories_fish_cat_dog_hamster_54.mp3",
  "Which pet is the SECOND most popular?": "/assets/audio/which_pet_is_the_second_most_popular_55.mp3",
  "First find the MOST popular pet (Fish = 12). Now find the next tallest bar.": "/assets/audio/first_find_the_most_popular_pet_fish_12_now_find_the_next_tallest_bar_56.mp3",
  "After Fish (12), the next tallest bar is Dog (8).": "/assets/audio/after_fish_12_the_next_tallest_bar_is_dog_8_57.mp3",
  "How many Rainy days were there in April?": "/assets/audio/how_many_rainy_days_were_there_in_april_58.mp3",
  "Find the Rainy bar and trace it to the scale.": "/assets/audio/find_the_rainy_bar_and_trace_it_to_the_scale_59.mp3",
  "The scale here jumps in steps of 3: 0, 3, 6, 9...": "/assets/audio/the_scale_here_jumps_in_steps_of_3_0_3_6_9_60.mp3",
  "This graph's scale goes up in steps of 3 (0, 3, 6, 9, 12, 15). What value sits exactly halfway between the 6 and 9 gridlines?": "/assets/audio/this_graphs_scale_goes_up_in_steps_of_3_0_3_6_9_12_15_what_value_sits_exactly_halfway_between_the_6_and_9_gridlines_61.mp3",
  "Halfway between 6 and 9 is the middle of that gap.": "/assets/audio/halfway_between_6_and_9_is_the_middle_of_that_gap_62.mp3",
  "(6 + 9) divided by 2 = 7.5": "/assets/audio/6_9_divided_by_2_75_63.mp3",
  "April has 30 days. How many days were NOT sunny?": "/assets/audio/april_has_30_days_how_many_days_were_not_sunny_64.mp3",
  "Sunny days = 15. Subtract from the total days in April (30).": "/assets/audio/sunny_days_15_subtract_from_the_total_days_in_april_30_65.mp3",
  "30 minus 15 = ?": "/assets/audio/30_minus_15_141.mp3",
  "Which type of weather happened LEAST often?": "/assets/audio/which_type_of_weather_happened_least_often_67.mp3",
  "Find the shortest bar in the graph.": "/assets/audio/find_the_shortest_bar_in_the_graph_68.mp3",
  "Rainy only reaches 6, the lowest of the three bars.": "/assets/audio/rainy_only_reaches_6_the_lowest_of_the_three_bars_69.mp3",
  "How many more Sunny days were there than Cloudy days?": "/assets/audio/how_many_more_sunny_days_were_there_than_cloudy_days_70.mp3",
  "Sunny = 15, Cloudy = 9. Subtract.": "/assets/audio/sunny_15_cloudy_9_subtract_71.mp3",
  "15 minus 9 = ?": "/assets/audio/15_minus_9_72.mp3",
  "True or False: A bar graph's scale must always start counting from 0.": "/assets/audio/true_or_false_a_bar_graphs_scale_must_always_start_counting_from_0_73.mp3",
  "Think about what would happen if a scale started at, say, 5.": "/assets/audio/think_about_what_would_happen_if_a_scale_started_at_say_5_74.mp3",
  "Starting at 0 keeps every bar's height honest and comparable.": "/assets/audio/starting_at_0_keeps_every_bars_height_honest_and_comparable_75.mp3",
  "How many medals were won altogether by all 4 teams?": "/assets/audio/how_many_medals_were_won_altogether_by_all_4_teams_76.mp3",
  "Add up Red + Blue + Green + Yellow.": "/assets/audio/add_up_red_blue_green_yellow_77.mp3",
  "10 + 4 + 6 + 8 = ?": "/assets/audio/10_4_6_8_78.mp3",
  "How many more medals did the Red team win than the Blue team?": "/assets/audio/how_many_more_medals_did_the_red_team_win_than_the_blue_team_79.mp3",
  "Red = 10, Blue = 4. Subtract.": "/assets/audio/red_10_blue_4_subtract_80.mp3",
  "10 minus 4 = ?": "/assets/audio/10_minus_4_81.mp3",
  "Which team came in 2nd place (second highest medal count)?": "/assets/audio/which_team_came_in_2nd_place_second_highest_medal_count_82.mp3",
  "1st place is Red with 10. Which team is next tallest?": "/assets/audio/1st_place_is_red_with_10_which_team_is_next_tallest_83.mp3",
  "Yellow has 8 medals, just behind Red.": "/assets/audio/yellow_has_8_medals_just_behind_red_84.mp3",
  "How many medals did the Green team win?": "/assets/audio/how_many_medals_did_the_green_team_win_85.mp3",
  "Find the Green bar and read across to the scale.": "/assets/audio/find_the_green_bar_and_read_across_to_the_scale_86.mp3",
  "The Green bar reaches the 6 gridline.": "/assets/audio/the_green_bar_reaches_the_6_gridline_87.mp3",
  "If Red and Blue's medals were combined into ONE team, how many medals would that team have?": "/assets/audio/if_red_and_blues_medals_were_combined_into_one_team_how_many_medals_would_that_team_have_88.mp3",
  "Red = 10, Blue = 4. Add them together.": "/assets/audio/red_10_blue_4_add_them_together_89.mp3",
  "10 + 4 = ?": "/assets/audio/10_4_90.mp3",
  "What is the y-axis measuring in this graph?": "/assets/audio/what_is_the_yaxis_measuring_in_this_graph_91.mp3",
  "The y-axis is the vertical line with numbers on it.": "/assets/audio/the_yaxis_is_the_vertical_line_with_numbers_on_it_92.mp3",
  "It's labelled with the value being measured — medals!": "/assets/audio/its_labelled_with_the_value_being_measured_medals_93.mp3",
  "The scale jumps by 5. If Fiction books = 15, which gridline should the Fiction bar's top touch?": "/assets/audio/the_scale_jumps_by_5_if_fiction_books_15_which_gridline_should_the_fiction_bars_top_touch_94.mp3",
  "Count gridlines from 0: 5, 10, 15, 20, 25.": "/assets/audio/count_gridlines_from_0_5_10_15_20_25_95.mp3",
  "15 is the third jump of 5 from zero.": "/assets/audio/15_is_the_third_jump_of_5_from_zero_96.mp3",
  "How many History books were borrowed?": "/assets/audio/how_many_history_books_were_borrowed_97.mp3",
  "Find the shortest bar — that's History.": "/assets/audio/find_the_shortest_bar_thats_history_98.mp3",
  "It only reaches the first gridline: 5.": "/assets/audio/it_only_reaches_the_first_gridline_5_99.mp3",
  "How many books were borrowed in total this week?": "/assets/audio/how_many_books_were_borrowed_in_total_this_week_100.mp3",
  "Add all 4 bars: Comics + Fiction + Science + History.": "/assets/audio/add_all_4_bars_comics_fiction_science_history_101.mp3",
  "25 + 15 + 10 + 5 = ?": "/assets/audio/25_15_10_5_102.mp3",
  "Which genre was borrowed the MOST?": "/assets/audio/which_genre_was_borrowed_the_most_103.mp3",
  "Look for the tallest bar.": "/assets/audio/look_for_the_tallest_bar_119.mp3",
  "Comics reaches the top gridline at 25.": "/assets/audio/comics_reaches_the_top_gridline_at_25_105.mp3",
  "A new genre, Poetry, was borrowed 20 times. Where would its bar sit compared to the others?": "/assets/audio/a_new_genre_poetry_was_borrowed_20_times_where_would_its_bar_sit_compared_to_the_others_106.mp3",
  "Comics = 25, Fiction = 15. Where does 20 fit?": "/assets/audio/comics_25_fiction_15_where_does_20_fit_107.mp3",
  "20 is more than 15 but less than 25.": "/assets/audio/20_is_more_than_15_but_less_than_25_108.mp3",
  "How many more Comics were borrowed than Science books?": "/assets/audio/how_many_more_comics_were_borrowed_than_science_books_109.mp3",
  "Comics = 25, Science = 10. Subtract.": "/assets/audio/comics_25_science_10_subtract_110.mp3",
  "25 minus 10 = ?": "/assets/audio/25_minus_10_111.mp3",
  "The Ice-Cream data has values up to 20. Which scale step would make the NEATEST graph?": "/assets/audio/the_icecream_data_has_values_up_to_20_which_scale_step_would_make_the_neatest_graph_112.mp3",
  "A good scale should divide evenly into the highest value and not need too many gridlines.": "/assets/audio/a_good_scale_should_divide_evenly_into_the_highest_value_and_not_need_too_many_gridlines_113.mp3",
  "20 divided by 4 = 5 gridlines exactly — nice and neat!": "/assets/audio/20_divided_by_4_5_gridlines_exactly_nice_and_neat_114.mp3",
  "How many cups of Mint ice-cream were sold?": "/assets/audio/how_many_cups_of_mint_icecream_were_sold_115.mp3",
  "Find the Mint bar — it's the shortest one.": "/assets/audio/find_the_mint_bar_its_the_shortest_one_116.mp3",
  "It reaches the second gridline: 8.": "/assets/audio/it_reaches_the_second_gridline_8_117.mp3",
  "Which flavour sold the MOST cups?": "/assets/audio/which_flavour_sold_the_most_cups_118.mp3",
  "Chocolate reaches the very top: 20.": "/assets/audio/chocolate_reaches_the_very_top_20_120.mp3",
  "How many cups of ice-cream were sold altogether today?": "/assets/audio/how_many_cups_of_icecream_were_sold_altogether_today_121.mp3",
  "Add Chocolate + Vanilla + Strawberry + Mint.": "/assets/audio/add_chocolate_vanilla_strawberry_mint_122.mp3",
  "20 + 12 + 16 + 8 = ?": "/assets/audio/20_12_16_8_123.mp3",
  "How many more Strawberry cups were sold than Vanilla cups?": "/assets/audio/how_many_more_strawberry_cups_were_sold_than_vanilla_cups_124.mp3",
  "Strawberry = 16, Vanilla = 12. Subtract.": "/assets/audio/strawberry_16_vanilla_12_subtract_125.mp3",
  "16 minus 12 = ?": "/assets/audio/16_minus_12_126.mp3",
  "True or False: All bars in a good bar graph must be the same width.": "/assets/audio/true_or_false_all_bars_in_a_good_bar_graph_must_be_the_same_width_127.mp3",
  "Only the HEIGHT should change between bars, not the width.": "/assets/audio/only_the_height_should_change_between_bars_not_the_width_128.mp3",
  "Equal width keeps the graph fair and easy to compare.": "/assets/audio/equal_width_keeps_the_graph_fair_and_easy_to_compare_129.mp3",
  "What should the TITLE of this graph tell the reader?": "/assets/audio/what_should_the_title_of_this_graph_tell_the_reader_130.mp3",
  "A title acts like the headline of a newspaper article.": "/assets/audio/a_title_acts_like_the_headline_of_a_newspaper_article_131.mp3",
  "It should summarise the graph's subject in a few words.": "/assets/audio/it_should_summarise_the_graphs_subject_in_a_few_words_132.mp3",
  "How many buses passed the school gate?": "/assets/audio/how_many_buses_passed_the_school_gate_133.mp3",
  "Find the Buses bar and read the scale.": "/assets/audio/find_the_buses_bar_and_read_the_scale_134.mp3",
  "It reaches the second gridline: 10.": "/assets/audio/it_reaches_the_second_gridline_10_135.mp3",
  "If you forgot to label the x-axis, what problem would happen?": "/assets/audio/if_you_forgot_to_label_the_xaxis_what_problem_would_happen_136.mp3",
  "Labels tell you WHICH category each bar belongs to.": "/assets/audio/labels_tell_you_which_category_each_bar_belongs_to_137.mp3",
  "Without labels, the bars become a mystery!": "/assets/audio/without_labels_the_bars_become_a_mystery_138.mp3",
  "How many more Cars passed than Bikes?": "/assets/audio/how_many_more_cars_passed_than_bikes_139.mp3",
  "Cars = 30, Bikes = 15. Subtract.": "/assets/audio/cars_30_bikes_15_subtract_140.mp3",
  "How many vehicles were counted in total?": "/assets/audio/how_many_vehicles_were_counted_in_total_142.mp3",
  "Add Cars + Buses + Bikes + Lorries.": "/assets/audio/add_cars_buses_bikes_lorries_143.mp3",
  "30 + 10 + 15 + 5 = ?": "/assets/audio/30_10_15_5_144.mp3",
  "Which vehicle type was seen the LEAST?": "/assets/audio/which_vehicle_type_was_seen_the_least_145.mp3",
  "Find the shortest bar.": "/assets/audio/find_the_shortest_bar_146.mp3",
  "Lorries only reaches 5, the lowest bar.": "/assets/audio/lorries_only_reaches_5_the_lowest_bar_147.mp3",
  "A bar in this graph reaches the value 10. Which food does it represent?": "/assets/audio/a_bar_in_this_graph_reaches_the_value_10_which_food_does_it_represent_148.mp3",
  "Scan each bar's height and find the one that stops at exactly 10.": "/assets/audio/scan_each_bars_height_and_find_the_one_that_stops_at_exactly_10_149.mp3",
  "Noodles = 14, Rice = 10, Sandwich = 6, Salad = 2.": "/assets/audio/noodles_14_rice_10_sandwich_6_salad_2_150.mp3",
  "Which food's bar is exactly TWICE as tall as the Sandwich bar?": "/assets/audio/which_foods_bar_is_exactly_twice_as_tall_as_the_sandwich_bar_151.mp3",
  "Sandwich = 6. What is 6 multiplied by 2?": "/assets/audio/sandwich_6_what_is_6_multiplied_by_2_152.mp3",
  "6 x 2 = 12... check each bar again: Rice = 10. Look for the bar closest to double.": "/assets/audio/6_x_2_12_check_each_bar_again_rice_10_look_for_the_bar_closest_to_double_153.mp3",
  "How many students were surveyed about their lunch choice in total?": "/assets/audio/how_many_students_were_surveyed_about_their_lunch_choice_in_total_154.mp3",
  "Add Noodles + Rice + Sandwich + Salad.": "/assets/audio/add_noodles_rice_sandwich_salad_155.mp3",
  "14 + 10 + 6 + 2 = ?": "/assets/audio/14_10_6_2_156.mp3",
  "How many more students chose Noodles than Salad?": "/assets/audio/how_many_more_students_chose_noodles_than_salad_157.mp3",
  "Noodles = 14, Salad = 2. Subtract.": "/assets/audio/noodles_14_salad_2_subtract_158.mp3",
  "14 minus 2 = ?": "/assets/audio/14_minus_2_159.mp3",
  "If the Sandwich bar suddenly grew by 4 more votes, what would its new value be?": "/assets/audio/if_the_sandwich_bar_suddenly_grew_by_4_more_votes_what_would_its_new_value_be_160.mp3",
  "Sandwich currently = 6. Add 4 more votes.": "/assets/audio/sandwich_currently_6_add_4_more_votes_161.mp3",
  "6 + 4 = ?": "/assets/audio/6_4_162.mp3",
  "Put these foods in order from MOST chosen to LEAST chosen.": "/assets/audio/put_these_foods_in_order_from_most_chosen_to_least_chosen_163.mp3",
  "Order the bar heights from tallest to shortest.": "/assets/audio/order_the_bar_heights_from_tallest_to_shortest_164.mp3",
  "14, 10, 6, 2 — already from biggest to smallest!": "/assets/audio/14_10_6_2_already_from_biggest_to_smallest_165.mp3",
  "Put the steps of making a bar graph in the CORRECT order.": "/assets/audio/put_the_steps_of_making_a_bar_graph_in_the_correct_order_166.mp3",
  "You must know your data BEFORE you can decide on a scale.": "/assets/audio/you_must_know_your_data_before_you_can_decide_on_a_scale_167.mp3",
  "The frame (axes) comes early, then scale, then the bars themselves, then labels.": "/assets/audio/the_frame_axes_comes_early_then_scale_then_the_bars_themselves_then_labels_168.mp3",
  "How many students travel to school by Bicycle?": "/assets/audio/how_many_students_travel_to_school_by_bicycle_169.mp3",
  "Find the shortest bar — Bicycle.": "/assets/audio/find_the_shortest_bar_bicycle_170.mp3",
  "It reaches the first gridline: 3.": "/assets/audio/it_reaches_the_first_gridline_3_171.mp3",
  "How many students were surveyed about how they travel to school?": "/assets/audio/how_many_students_were_surveyed_about_how_they_travel_to_school_172.mp3",
  "Add Bus + Walk + Car + Bicycle.": "/assets/audio/add_bus_walk_car_bicycle_173.mp3",
  "18 + 12 + 9 + 3 = ?": "/assets/audio/18_12_9_3_174.mp3",
  "How many more students take the Bus than Walk?": "/assets/audio/how_many_more_students_take_the_bus_than_walk_175.mp3",
  "Bus = 18, Walk = 12. Subtract.": "/assets/audio/bus_18_walk_12_subtract_176.mp3",
  "18 minus 12 = ?": "/assets/audio/18_minus_12_177.mp3",
  "The travel data goes up to 18. Which scale step avoids wasted space AND divides evenly?": "/assets/audio/the_travel_data_goes_up_to_18_which_scale_step_avoids_wasted_space_and_divides_evenly_178.mp3",
  "18 should divide evenly by the step size for a neat top gridline.": "/assets/audio/18_should_divide_evenly_by_the_step_size_for_a_neat_top_gridline_179.mp3",
  "18 divided by 3 = 6 gridlines exactly.": "/assets/audio/18_divided_by_3_6_gridlines_exactly_180.mp3",
  "Which is the MOST common way to travel to school?": "/assets/audio/which_is_the_most_common_way_to_travel_to_school_181.mp3",
  "Find the tallest bar.": "/assets/audio/find_the_tallest_bar_182.mp3",
  "Bus reaches the highest point at 18.": "/assets/audio/bus_reaches_the_highest_point_at_18_183.mp3",
  "Which club has EXACTLY 3 times as many members as the Chess club?": "/assets/audio/which_club_has_exactly_3_times_as_many_members_as_the_chess_club_184.mp3",
  "Chess = 4 members. What is 4 multiplied by 3?": "/assets/audio/chess_4_members_what_is_4_multiplied_by_3_185.mp3",
  "4 x 3 = 12. Which club has exactly 12 members?": "/assets/audio/4_x_3_12_which_club_has_exactly_12_members_186.mp3",
  "How many students are in a club altogether?": "/assets/audio/how_many_students_are_in_a_club_altogether_187.mp3",
  "Add Art + Coding + Music + Drama + Chess.": "/assets/audio/add_art_coding_music_drama_chess_188.mp3",
  "16 + 24 + 8 + 12 + 4 = ?": "/assets/audio/16_24_8_12_4_189.mp3",
  "How many more members does Coding Club have than Art Club?": "/assets/audio/how_many_more_members_does_coding_club_have_than_art_club_190.mp3",
  "Coding = 24, Art = 16. Subtract.": "/assets/audio/coding_24_art_16_subtract_191.mp3",
  "24 minus 16 = ?": "/assets/audio/24_minus_16_192.mp3",
  "If Music and Chess clubs merged into one club, would their new total be bigger or smaller than the Art club?": "/assets/audio/if_music_and_chess_clubs_merged_into_one_club_would_their_new_total_be_bigger_or_smaller_than_the_art_club_193.mp3",
  "Music = 8, Chess = 4. Add them, then compare to Art (16).": "/assets/audio/music_8_chess_4_add_them_then_compare_to_art_16_194.mp3",
  "8 + 4 = 12, which is less than 16.": "/assets/audio/8_4_12_which_is_less_than_16_195.mp3",
  "Order the clubs from LARGEST to SMALLEST.": "/assets/audio/order_the_clubs_from_largest_to_smallest_196.mp3",
  "Order the bar values from biggest to smallest: 24, 16, 12, 8, 4.": "/assets/audio/order_the_bar_values_from_biggest_to_smallest_24_16_12_8_4_197.mp3",
  "Coding=24, Art=16, Drama=12, Music=8, Chess=4.": "/assets/audio/coding24_art16_drama12_music8_chess4_198.mp3",
  "A new bar graph has NO scale drawn yet, only bars. What problem would this cause?": "/assets/audio/a_new_bar_graph_has_no_scale_drawn_yet_only_bars_what_problem_would_this_cause_199.mp3",
  "The scale is what turns bar height into a readable number.": "/assets/audio/the_scale_is_what_turns_bar_height_into_a_readable_number_200.mp3",
  "Without gridlines and numbers, you can only guess which bar is taller.": "/assets/audio/without_gridlines_and_numbers_you_can_only_guess_which_bar_is_taller_201.mp3",
  "Which two clubs COMBINED have the same total members as the Coding Club alone?": "/assets/audio/which_two_clubs_combined_have_the_same_total_members_as_the_coding_club_alone_202.mp3",
  "Coding = 24. Try adding pairs of other clubs to see which equals 24.": "/assets/audio/coding_24_try_adding_pairs_of_other_clubs_to_see_which_equals_24_203.mp3",
  "Art (16) + Music (8) = 24. That matches!": "/assets/audio/art_16_music_8_24_that_matches_204.mp3"
};